consul:
  extends:
    file: common.yml
    service: consul
  restart: always
registrator:
  extends:
    file: common.yml
    service: registrator
  links:
    - consul:consul
  restart: always
db:
  extends:
    file: common.yml
    service: db
  container_name: prod-db
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  restart: always
pdv:
  extends:
    file: common.yml
    service: pdv
  environment:
    - PLATFORM=prod
  links:
    - consul:consul
  restart: always
caisse:
  extends:
    file: common.yml
    service: caisse
  environment:
    - PLATFORM=prod
  links:
    - consul:consul
  volumes:
    - /root/tickets:/esc-caisse/tickets
  restart: always
adm:
  extends:
    file: common.yml
    service: adm
  environment:
    - PLATFORM=prod
  links:
    - consul:consul
  restart: always
smtp:
  extends:
    file: common.yml
    service: smtp
  links:
    - consul:consul
  restart: always
back:
  image: hub.softinnov.com/esc-back
  extends:
    file: common.yml
    service: back
  links:
    - consul:consul
  restart: always
sync:
  extends:
    file: common.yml
    service: sync
  links:
    - consul:consul
  volumes:
    - /root/tickets:/tickets
  restart: always
client:
  extends:
    file: common.yml
    service: client
  ports:
    - "80:80"
    - "443:443"
  links:
    - consul:consul
  volumes:
    - /etc/ssl/private:/etc/ssl/private
  restart: always
monitor:
  image: softinnov/bearded-monitor
  privileged: true
  pid: host
  command: "-p 95 -i 30s -s usr1 chey_pdv chey_caisse chey_adm"
  restart: always
